apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-server
  labels:
    app: code-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: code-server
  template:
    metadata:       
      labels:
        app: code-server
    spec:
      containers:  
        - name: code-server
          image: lscr.io/linuxserver/code-server:latest 
          ports:
            - containerPort: 8443
          volumeMounts:
            - name: config
              mountPath: /config
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: pvc-dynamic
